### ISSUE TITLE
A rough checklist for the finality proof.

### ISSUE THREAD

**Issue by mcalancea** [runtimeverification/casper-cbc-proofs#196]
- [x] Initial definitions and statement.
- [ ] Proof of inequality (1). 
  + [x] Definitions of `V_k` `Veq` and `Vchange` and results about their relations (like `Veq` and `Vchange` disjoint).
  + [ ] General results connecting set relations to size relations (WIP).
  + [ ] General results about orders (WIP).
- [ ] Obtaining `u'` and Proof of inequality (2).
- [ ] Connecting inequalities (1) and (2).
- [ ] Prove that `A(u')`, `Veq` and `Vchange` all included in `A(u)`.
- [ ] Prove that `A(u')` and `Vchange` disjoint.
- [ ] Bringing it home.
